[package]
name = "multiple_ownership"
version = "0.1.0"
authors = ["Diego Castillo <raigiku@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
